import {
  Camera,
  Video,
  Palette,
  Film,
  Clapperboard,
  Layers,
  Monitor,
  Aperture,
  Play,
  PenTool,
  Mountain,
  Mic,
  Layout,
  User,
  Tv,
  Printer,
  ShoppingBag,
  Scissors,
  Sparkles,
  Smartphone,
  Baby,
} from "lucide-react";

export const iconMap = {
  camera: Camera,
  sparkles:Sparkles,
  video: Video,
  palette: Palette,
  film: Film,
  clapperboard: Clapperboard,
  layers: Layers,
  monitor: Monitor,
  aperture: Aperture,
  play: Play,
  "pen-tool": PenTool, 
  mountain: Mountain,
  mic: Mic,
  layout: Layout,
  user: User,
  tv: Tv,
  printer: Printer,
  "shopping-bag": ShoppingBag,
  scissors: Scissors,
  smartphone: Smartphone,
  baby: Baby,
};
